project:
  type: website

# see https://ucsb-meds.github.io/customizing-quarto-websites for lots of helpful tips

website:
  title: "PGS methods competition"
  site-url: 'https://methodscomparison.intervenegeneticscores.org/'
  site-path: '/'
  navbar:
    tools:
    - icon: twitter
      href: https://twitter.com/intervene_eu
    - icon: github
      menu:
        - text: Source
          url:  https://github.com/intervene-EU-H2020/pgs-method-compare
        - text: Report a bug
          url:  https://github.com/intervene-EU-H2020/pgs-method-compare/issues/new
    left:
      - href: index.qmd
        text: About
      - href: leaderboard.qmd
        text: Leaderboards
      - href: meta.qmd
        text: Meta analysis
      - href: effect-sizes.qmd
        text: Absolute effect sizes
      - href: relative.qmd
        text: Relative effect sizes
      - href: tutorials.qmd
        text: Tutorials and guidance
      - href: glossary.qmd
        text: Glossary
      - href: acknowledgements.qmd
        text: Acknowledgements

format:
  html:
    theme: styles.scss
    css: [https://assets.emblstatic.net/vf/v2.5.20/css/styles.css, styles.css]
    mainfont: IBM Plex Sans
    toc: true
    doi: 10.1016/j.ajhg.2024.06.003
    date-modified: today
    include-after-body: footer.html
    
editor: visual

