project:
  type: website

website:
  title: "PRS method benchmarks"
  navbar:
    tools:
    - icon: twitter
      href: https://twitter.com/intervene_eu
    - icon: github
      menu:
        - text: Source
          url:  https://github.com/intervene-EU-H2020/prs-method-compare
        - text: Report a bug
          url:  https://github.com/intervene-EU-H2020/prs-method-compare/issues/new
    left:
      - href: index.qmd
        text: Home
      - href: effect-sizes.qmd
        text: Effect sizes
      - href: pairwise.qmd
        text: Pairwise comparison
      - href: meta.qmd
        text: Meta analysis
      - href: glossary.qmd
        text: Glossary
  page-footer: |
    This project has received funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No 101016775

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    doi: DOI-XXX
    date-modified: today
    
editor: visual

