project:
  type: website

website:
  title: "PGS method competition"
  site-url: 'https://methodscomparison.intervenegeneticscores.org/'
  site-path: '/'
  navbar:
    tools:
    - icon: twitter
      href: https://twitter.com/intervene_eu
    - icon: github
      menu:
        - text: Source
          url:  https://github.com/intervene-EU-H2020/pgs-method-compare
        - text: Report a bug
          url:  https://github.com/intervene-EU-H2020/pgs-method-compare/issues/new
    left:
      - href: index.qmd
        text: Home
      - href: effect-sizes.qmd
        text: Effect sizes
      - href: pairwise.qmd
        text: Pairwise comparison
      - href: meta.qmd
        text: Meta analysis
      - href: leaderboard.qmd
        text: Leaderboard        
      - href: tutorials.qmd
        text: Tutorials
      - href: glossary.qmd
        text: Glossary
      - href: acknowledgements.qmd
        text: Acknowledgements
  page-footer: |
    This project has received funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No 101016775

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    doi: 10.1016/j.ajhg.2024.06.003
    date-modified: today
    
editor: visual

