project:
  type: website

website:
  title: "prs-method-document"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  body-footer: |
    This project has received funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No 101016775

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

