name: Render on release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2

      - name: Install Quarto
        run: |
          sudo apt-get update
          sudo apt-get install -y quarto

      - name: Render Quarto project
        run: |
          quarto render

      - name: Upload Rendered Artefact
        uses: actions/upload-artifact@v4
        with:
          name: quarto-build
          path: _site/
