on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

env:
  RENV_CONFIG_SANDBOX_ENABLED: FALSE
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:        
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render website
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
        
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: d67af2e6153b82c798b018f38642d480
          projectName: prs-method-compare
          directory: _site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          
